ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE LABO_TRANSACCIONES_RELACIONAL 
DATAFILE 'labo_transacciones_relacional_01.dbf' 
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE 200M;

CREATE USER LAB_TRANSACCIONES_RELACION_USR IDENTIFIED BY Laboratorio
DEFAULT TABLESPACE LABO_TRANSACCIONES_RELACIONAL
QUOTA UNLIMITED ON LABO_TRANSACCIONES_RELACIONAL;

GRANT CONNECT, RESOURCE, CREATE VIEW TO LAB_TRANSACCIONES_RELACION_USR;