BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COUNTRIES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/
--FALTA REPETIR PARA LAS OTRAS TABLAS
--------------------------------------------------------------------------------

CREATE TABLE JOBS (
    JOB_ID      VARCHAR2(10)    NOT NULL,
    JOB_TITLE   VARCHAR2(35)    NOT NULL,
    MIN_SALARY  NUMBER(6)       DEFAULT NULL,
    MAX_SALARY  NUMBER(6)       DEFAULT NULL
);

ALTER TABLE JOBS
ADD CONSTRAINT PK_JOBS
PRIMARY KEY (JOB_ID);
--------------------------------------------------------------------------------

CREATE TABLE REGIONS (
    REGION_ID   NUMBER          NOT NULL,
    REGION_NAME VARCHAR2(25)    DEFAULT NULL
);

ALTER TABLE REGIONS
ADD CONSTRAINT PK_REGIONS
PRIMARY KEY (REGION_ID);

--------------------------------------------------------------------------------

CREATE TABLE COUNTRIES (
    COUNTRY_ID      CHAR(2)         NOT NULL,
    COUNTRY_NAME    VARCHAR2(40)    DEFAULT NULL,
    REGION_ID       NUMBER
);

ALTER TABLE COUNTRIES
ADD CONSTRAINT PK_COUNTRIES
PRIMARY KEY (COUNTRY_ID);

ALTER TABLE COUNTRIES
ADD CONSTRAINT FK_COUNTRIES_REGION
FOREIGN KEY (REGION_ID)
REFERENCES REGIONS (REGION_ID);

--------------------------------------------------------------------------------

CREATE TABLE LOCATIONS (
    LOCATION_ID     NUMBER(4)       NOT NULL,
    STREET_ADDRESS  VARCHAR2(40)    DEFAULT NULL,
    POSTAL_CODE     VARCHAR2(12)    DEFAULT NULL,
    CITY            VARCHAR2(30)    NOT NULL,
    STATE_PROVINCE  VARCHAR2(25)    DEFAULT NULL,
    COUNTRY_ID      CHAR(2)         DEFAULT NULL
);

ALTER TABLE LOCATIONS
ADD CONSTRAINT PK_LOCATIONS
PRIMARY KEY (LOCATION_ID);

ALTER TABLE LOCATIONS
ADD CONSTRAINT FK_LOCATIONS_COUNTRIES
FOREIGN KEY (COUNTRY_ID)
REFERENCES COUNTRIES (COUNTRY_ID);

--------------------------------------------------------------------------------

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID     NUMBER(4)       NOT NULL,
    FIRST_NAME      VARCHAR2(20)    DEFAULT NULL,
    LAST_NAME       VARCHAR2(25)    NOT NULL,
    EMAIL           VARCHAR2(25)    NOT NULL,
    PHONE_NUMBER    VARCHAR2(20)    DEFAULT NULL,
    HIRE_DATE       DATE            NOT NULL,
    JOB_ID          VARCHAR2(10)    NOT NULL,
    SALARY          NUMBER(8,2)     DEFAULT 0,
    COMMISSION_PCT  NUMBER(2,2)     DEFAULT NULL,
    MANAGER_ID      NUMBER(6)       DEFAULT NULL,
    DEPARTMENT_ID   NUMBER(4)       DEFAULT NULL
);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT PK_EMPLOYEES
PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_JOBS
FOREIGN KEY (JOB_ID)
REFERENCES JOBS (JOB_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_DEPARTMENTS
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_MANAGER
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES (EMPLOYEE_ID);

--------------------------------------------------------------------------------

CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID NUMBER(6)    NOT NULL,
    START_DATE  DATE         NOT NULL,
    END_DATE    DATE         NOT NULL,
    JOB_ID      VARCHAR2(10) NOT NULL,
    DEPARTMENT  NUMBER(4)    DEFAULT NULL
);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_EMPLOYEES
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_JOBS
FOREIGN KEY (JOB_ID)
REFERENCES JOBS (JOB_ID);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT PK_JOB_HISTORY
PRIMARY KEY (EMPLOYEE_ID, JOB_ID);

--------------------------------------------------------------------------------

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(4)       NOT NULL,
    DEPARTMENT_NAME VARCHAR2(30)    NOT NULL,
    MANAGER_ID      NUMBER(6)       DEFAULT NULL,
    LOCATION_ID     NUMBER(4)       DEFAULT NULL
);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT PK_DEPARTMENTS
PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_EMPLOYEES
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_LOCATIONS
FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATIONS (LOCATION_ID);