    CREATE TABLE S (
        S#     VARCHAR2(4) PRIMARY KEY,
        SNAME  VARCHAR2(30) NOT NULL,
        STATUS NUMBER(2),
        CITY   VARCHAR2(20) NOT NULL
    );
    
    CREATE TABLE P (
        P#     VARCHAR2(4) PRIMARY KEY,
        PNAME  VARCHAR2(30) NOT NULL,
        COLOR  VARCHAR2(10) NOT NULL,
        WEIGHT NUMBER(5, 2) NOT NULL,
        CITY   VARCHAR2(20) NOT NULL
    );
    
    CREATE TABLE SP (
        S#  VARCHAR2(4) NOT NULL,
        P#  VARCHAR2(4) NOT NULL,
        QTY NUMBER(6) NOT NULL,
        CONSTRAINT PK_SP PRIMARY KEY (S#, P#), 
        
        CONSTRAINT FK_SP_S FOREIGN KEY (S#) REFERENCES S(S#),
        CONSTRAINT FK_SP_P FOREIGN KEY (P#) REFERENCES P(P#)
    );
    
    CREATE TABLE J (
        J#    VARCHAR2(4) PRIMARY KEY,
        JNAME VARCHAR2(30) NOT NULL,
        CITY  VARCHAR2(20) NOT NULL
    );
    
    CREATE TABLE SPJ (
        S#  VARCHAR2(4) NOT NULL,
        P#  VARCHAR2(4) NOT NULL,
        J#  VARCHAR2(4) NOT NULL,
        QTY NUMBER(6) NOT NULL,
        
        CONSTRAINT PK_SPJ PRIMARY KEY (S#, P#, J#),
        CONSTRAINT FK_SPJ_S FOREIGN KEY (S#) REFERENCES S(S#),
        CONSTRAINT FK_SPJ_P FOREIGN KEY (P#) REFERENCES P(P#),
        CONSTRAINT FK_SPJ_J FOREIGN KEY (J#) REFERENCES J(J#)
    );